version: '3.7'
services:
  app:
    build: .
    init: true
    environment:
      - VIRTUAL_HOST=localhost
  redis:
    image: redis:4
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "5000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=localhost
